/* Copyright © 2016 EIS Group and/or one of its affiliates. All rights reserved. Unpublished work under U.S. copyright laws.
 CONFIDENTIAL AND TRADE SECRET INFORMATION. No portion of this work may be copied, distributed, modified, or incorporated into any other media without EIS Group prior written consent.*/
package com.exigen.ren.main.enums;

public final class BamConstants {

    public static final String ALERT_CREATE = "Create Alert %s for %s %s";
    public static final String ALERT_UPDATE = "Update Alert %s for %s %s";
    public static final String ALERT_DELETE = "Delete Alert %s for %s %s";
    public static final String ACCEPT_PAYMENT_CANCELED = "Accept Payment Type - for -";
    public static final String ACCEPT_PAYMENT_TYPE = "Accept Payment Type %s for %s";
    public static final String ADJUST_PREMIUM = "Adjust Premium for period %s";
    public static final String MODAL_PREMIUM_FOR_BILLING_GROUP = "Modal Premium for Billing group %s updated. Modal Premium Effective Date %s";
    public static final String ACCEPT_PAYMENT_TYPE_ADDED = "Payment method %s has been added, effective date: , expiration date:";
    public static final String ACCEPT_PAYMENT_TYPE_ADDED_WITH_DATE = "Payment method %s has been added, effective date: %s, expiration date: %s";
    public static final String ACCEPT_PAYMENT_TYPE_EDITED_WITH_DATE = "Payment method %s has been edited, effective date: %s, expiration date: %s";
    public static final String ACCEPT_PAYMENT_TYPE_DELETED_WITH_DATE = "Payment method %s has been deleted, effective date: %s, expiration date: %s";
    public static final String ACCEPT_PAYMENT_FINISHED = "Accept Payment for %s for Invoice #%s from Billing Account Suspense";
    public static final String ADD_DAMAGE = "Add Damage # %s for Claim # %s";
    public static final String ADD_SUSPENSE = "Add Suspense #%s for %s";
    public static final String ADD_PREMIUM_WAIVER = "Process Add Premium Waiver effective %s; for Policy %s effective %s";
    public static final String BIND_QUOTE = "Bind Quote effective %s for Quote %s effective %s";
    public static final String BULLETIN_CREATED = "Bulletin created";
    public static final String BULLETIN_SUBMITTED_DELETED = "Submitted bulletin deleted";
    public static final String BULLETIN_INQUIRY = "Bulletin inquiry";
    public static final String BULLETIN_SUBMETTED= "Bulletin submitted";
    public static final String BULLETIN_UPDATED= "Bulletin updated";
    public static final String CHANGE_BROKER_FOR_POLICY = "Change Broker for Policy %s effective %s from %s to %s completed successfully.";
    public static final String CHANGE_BROKER_REQUEST = "Change broker request for Policy %s effective %s";
    public static final String CHANGE_RENEWAL_LAPSE = "Change Renewal Lapse on Policy effective %s (%s) Transaction premium: %s for Policy %s";
    public static final String COMPANY_DECLINE = "Company Decline Quote %s effective %s (Account not target market)";
    public static final String CONTRACT_ACCEPTANCE_QUOTE = "Contract Acceptance Quote %s effective %s";
    public static final String CONTRACT_ACCEPTANCE_RENEWAL = "Contract Acceptance Renewal %s effective %s";
    public static final String COPY_QUOTE_FROM_POLICY = "Copy Quote %s effective %s from Policy %s";
    public static final String COPY_QUOTE_FROM_QUOTE = "Copy Quote %s from Quote %s effective %s";
    public static final String CORRESPONDENCE_GENERATION_INITIATED = "Correspondence Generation Initiated";
    public static final String CONSOLIDATED_STATEMENT_REMOVED = "Consolidated Statement setting enablement was removed.";
    public static final String CONSOLIDATED_STATEMENT_REMOVED_BA = "Consolidated Statement setting enablement from Billing Account #%s was removed.";
    public static final String CONSOLIDATED_STATEMENT_UPDATE = "Consolidated Statement setting was updated.";
    public static final String CONSOLIDATED_STATEMENT_UPDATE_BA = "Consolidated Statement setting from Billing Account #%s was updated.";
    public static final String CONSOLIDATED_STATEMENT_BA_WAS_ENABLED = "Consolidated Statement setting from Billing Account # was enabled.";
    public static final String CONSOLIDATED_STATEMENT_BA_NUM_WAS_ENABLED = "Consolidated Statement setting from Billing Account #%s was enabled.";
    public static final String CONSOLIDATED_STATEMENT_BA_NUM_IS_INITIATED = "Consolidated Statement generation for Billing Account #%s is initiated.";
    public static final String CONSOLIDATED_STATEMENT_BA_NUM_IS_GENERATED = "Consolidated Statement for Billing Account #%s is successfully generated.";
    public static final String CONSOLIDATED_STATEMENT_WAS_ENABLED = "Consolidated Statement setting was enabled.";
    public static final String CREATE_CASE_PROFILE = "Create Case Profile %s - %s";
    public static final String CREATE_CLAIM = "Create Claim # %s for Loss Date %s";
    public static final String CREATE_QUOTE = "Create Quote %s effective %s";
    public static final String CUSTOMER_DECLINE = "Customer Decline Quote %s effective %s";
    public static final String CANCELLED = "Cancelled";
    public static final String DELETE_CANCEL_NOTICE = "Delete Cancel Notice from Policy %s effective %s";
    public static final String DELETE_ENDORSEMENT = "Endorsement effective %s for Policy %s effective %s successfully deleted";
    public static final String DECLINE_PAYMENT_AMOUNT = "Decline payment amount %s";
    public static final String FINALIZE_CASE_PROFILE = "Finalize Case Profile %s - %s with status Active";
    public static final String FINISHED = "Finished";
    public static final String FLAGGED_MANUAL_RENEWAL = "Flagged \"Manual Renewal Only\" with reason Loss Experience for Policy %s effective %s";
    public static final String GENERATE_PROPOSAL_FOR_QUOTE = "Generate proposal for Quote %s effective %s";
    public static final String GENERATE_PROPOSAL_FOR_RENEWAL = "Generate proposal for Renewal %s effective %s";
    public static final String GENERATE_INVOICE_DUE = "Generate Invoice # Due for Billing Period";
    public static final String INITIATE_ENDORSEMENT = "Initiate Endorsement effective %s for Policy %s effective %s";
    public static final String INITIATE_ROLL_BACK_ENDORSEMENT = "Initiate Roll Back Endorsement effective %s for Policy %s effective %s";
    public static final String ISSUE_ANNIVERSARY_RENEWAL = "Issue anniversary renewal effective %s; Transaction Premium: %s for Policy %s effective %s";
    public static final String ISSUE_ENDORSEMENT = "Issue Endorsement effective %s; Transaction Premium: %s for Policy %s effective %s";
    public static final String ISSUE_MASTER_QUOTE = "Issue Master Quote effective %s; Transaction Premium: %s for Policy %s";
    public static final String ISSUE_QUOTE = "Issue Quote effective %s; Transaction Premium: %s for Policy %s";
    public static final String ISSUE_RENEWAL = "Issue Renewal effective %s; Transaction Premium: %s for Policy %s effective %s";
    public static final String NEW_VERSION_CASE_PROFILE = "New Version of Case Profile %s - %s created. Old Version expiration/New version effective date - %s";
    public static final String POLICY_AUTOMATICALLY_INITIATED_ENDORSEMENT = "Policy %s automatically initiated Premium Bearing endorsement on %s";
    public static final String POLICY_AUTOMATICALLY_INITIATED_RENEWAL = "Policy %s automatically initiated anniversary renewal on %s";
    public static final String POLICY_AUTOMATICALLY_ISSUED_RATED_ENDORSEMENT = "Policy %s automatically issued endorsement on %s";
    public static final String POLICY_AUTOMATICALLY_PROPOSED_RENEWAL = "Policy %s automatically proposed anniversary renewal on %s";
    public static final String POLICY_AUTOMATICALLY_RATED_ENDORSEMENT = "Policy %s automatically rated Premium Bearing endorsement on %s";
    public static final String POLICY_AUTOMATICALLY_RATED_RENEWAL = "Policy %s automatically rated anniversary renewal on %s";
    public static final String POLICY_BEARING_ENDORSEMENT = "Initiate Non-Premium Bearing Endorsement effective %s for Policy %s effective %s; Reason: Updated Insured and/or Interest Info";
    public static final String POLICY_CANCELLED_RESCINDED = "Policy# %s (%s) Cancelled with Effective Date %s has been Rescinded with amount = %s";
    public static final String POLICY_CREATION = "Policy %s effective %s from Quote %s";
    public static final String POLICY_EFFECTIVE_FROM_QUOTE = "Policy %1$s effective %2$s from Quote %1$s";
    public static final String POLICY_HAS_BEEN_CANCELLED = "Policy# %s (%s) has been Cancelled Flat, Reason: Insured Request - Due To High Premium, amount = %s";
    public static final String POLICY_HAS_BEEN_REWRITTEN = "Policy# %s (%s) has been rewritten from Cancelled Policy# %s with Effective Date %s, amount = %s";
    public static final String POLICY_SPLIT = "Policy %s has been split to a new quote";
    public static final String PREMIUM_ADJUSTMENT = "Premium Adjustment effective %s; Transaction Premium: %s for Policy %s";
    public static final String PROCESS_CANCELLATION = "Process Cancellation effective %s (%s) Transaction Premium: %s for Policy %s effective %s";
    public static final String PROCESS_CANCEL_NOTICE = "Process Cancel Notice effective %s for Policy %s";
    public static final String PROCESS_CHANGE_REINSTATEMENT_LAPSE_PERIOD = "Process Change Reinstatement Lapse Period effective %s (%s) Transaction Premium: %s for Policy %s effective %s";
    public static final String PROCESS_REINSURANCE_RATE_UPDATED = "Process Reinsurance Rate updated %s for Policy %s effective %s";
    public static final String PROCESS_REINSTATEMENT_EFFECTIVE = "Process Reinstatement effective %s (%s) Transaction Premium: %s for Policy %s effective %s";
    public static final String PROCESS_REINSTATEMENT_EFFECTIVE_WITHOUT_LAPSE =
            "Process Reinstatement effective %s (Without Lapse: payment received within grace period) Transaction Premium: %s for Policy %s effective %s";
    public static final String PROCESS_REINSTATEMENT_EFFECTIVE_WITH_LAPSE =
            "Process Reinstatement effective %s (Lapse: payment received within the lapse period) Transaction Premium: %s for Policy %s effective %s";
    public static final String PROCESS_REINSTATEMENT_NOTICE = "Process Cancel Notice effective %s for Policy %s";
    public static final String PROCESS_RESCIND_CANCELLATION = "Process Rescind Cancellation effective %s Transaction Premium: %s for Policy %s effective %s";
    public static final String REMOVE_FLAG_MANUAL_RENEWAL = "Removed Flag \"Manual Renewal Only\" for Policy %s effective %s";
    public static final String REMOVE_PREMIUM_WAIVER = "Process Remove Premium Waiver effective %s; for Policy %s effective %s";
    public static final String RENEW_EFFECTIVE = "Renew effective %s for Policy %s effective %s";
    public static final String REWRITTEN_QUOTE_FROM_CANCELLED = "Rewritten Quote %s effective %s from Cancelled %s";
    public static final String REWRITE_POLICY_TO_QUOTE = "Rewrite Policy %s to Quote %s effective %s";
    public static final String SUSPEND_QUOTE = "Suspend Quote %s";
    public static final String SUSPEND_STATUS_REMOVED_FOR_QUOTE = "Suspend status removed for Quote %s";
    public static final String SCHEME_APPROVAL_REQUEST = "Scheme %s %s Approval Requested";
    public static final String SCHEME_APPROVED = "Scheme %s %s Approved";
    public static final String SCHEME_CLOSED = "Scheme %s %s Closed";
    public static final String SCHEME_DISAPPROVE = "Scheme %s %s Disapproved";
    public static final String SCHEME_SET_RUNOFF = "Scheme %s %s Set to Run-Off";
    public static final String UPDATE_CASE_PROFILE = "Update Case Profile %s - %s";
    public static final String UPDATE_ENDORSEMENT = "Update Endorsement effective %s for Policy %s effective %s";
    public static final String UPDATE_QUOTE = "Update Quote %s";
    public static final String UPDATE_RENEWAL = "Update Renewal effective %s for Policy %s effective %s";
    public static final String UPDATE_PENDING = "Update Customer General data for Customer %s";
    public static final String UPDATE_EMPLOYMENT_INFO = "Update Group Relationship Employment for Customer %s";
    public static final String UPDATE_STUDENT_INFO  = "Update Group Relationship Student for Customer %s";
    public static final String UPDATE_MEMBERSHIP_INFO = "Update Group Relationship Membership for Customer %s";
    public static final String MERGED_FROM = "Merged From: ";
    public static final String MERGED_INTO = "Merged Into: ";
    public static final String UN_ALLOCATE_PAYMENT_AMOUNT = "Un-Allocate Payment Amount %s";
    public static final String INVOICE_STATUS_CHANGED_TO_ISSUED = "Invoice #%s status changed to Issued";
    public static final String INVOICE_STATUS_CHANGED_TO_PAID_IN_FULL = "Invoice #%s status changed to Paid in Full";
    public static final String INVOICE_STATUS_CHANGED_TO = "Invoice #%s status changed to %s";
    public static final String NON_PREMIUM_BA_CREATED = "Non-Premium Type Billing Account #%s is Created.";
    public static final String AUTOMATIC_RECURRING_PAYMENT = "Automatic Recurring Payment %s with effective date %s has been created.";
    public static final String REGENERATE_INVOICE = "Regenerate Invoice #%s";
    public static final String REGENERATE_INVOICE_WITHOUT = "Regenerate Invoice #";
    public static final String INVOICE_SUCCESSFULLY_GENERATED = "Invoice #%s Due %s for Billing Period %s is successfully generated";
    public static final String INVOICE_SUCCESSFULLY_GENERATED_FROM = "Invoice #%s Due %s for Billing Period %s is successfully generated from %s";
    public static final String INVOICE_GENERATE_CANCEL = "Generate Invoice # Due %s for Billing Period %s";
    public static final String INVOICE_GENERATE = "Generate Invoice #%s Due %s for Billing Period %s";
    public static final String INVOICE_GENERATE_FROM = "Generate Invoice #%s Due %s for Billing Period %s from %s";
    public static final String DISCARD_INVOICE = "Discard Invoice #%s Due %s for Billing Period %s";
    public static final String UPDATE_BILLING_ACCOUNT_SUSPENSE = "Update Billing Account Suspense #%s";
    public static final String ADD_BILLING_ACCOUNT_SUSPENSE = "Add Billing Account Suspense #%s for %s";
    public static final String BILLING_RECURRING_NOTICE ="Billing EFT/Recurring Withdrawal Notice for %s";
    public static final String BILLING_DRAFT_BILL_INITIATE ="Draft Bill Due %s generation for Billing Period %s - %s is initiated";
    public static final String BILLING_DRAFT_BILL_GENERATE ="Draft Bill Due %s for Billing Period %s - %s is successfully generated";
    public static final String BILLING_DRAFT_BILL_INITIATE_FROM ="Draft Bill Due %s generation for Billing Period %s - %s is initiated from %s";
    public static final String BILLING_DRAFT_BILL_GENERATE_FROM ="Draft Bill Due %s for Billing Period %s - %s is successfully generated from %s";
    public static final String REMOVE_SUSPENSE_FOR_BILLING_ACCOUNT = "Remove Suspense amount %s for Billing Account #%s";
    public static final String TRANSFER_PAYMENT_TO_BILLING_ACCOUNT = "Transfer Payment amount %s to Billing Account #%s";
    public static final String DRAFT_BILL_DUE_INITIATED = "Draft Bill Due generation for Billing Period is initiated";
    public static final String INQUIRY_REFUND = "Inquiry Refund for %s";
    public static final String REFUND_APPROVED = "Refund approved for %s";
    public static final String REFUND_INITIATED = "Refund initiated for %s";
    public static final String REFUND_APPROVED_AUTOMATICALLY = "Refund for %s approved automatically";
    public static final String REFUND_CREATED_TASK = "Task Created Refund Issue, %s";
    public static final String REFUND_DISAPPROVED = "Refund for %s disapproved";
    public static final String REFUND_ISSUED = "Refund for %s issued";
    public static final String REFUND_VOIDED = "Refund for %s voided";
    public static final String REFUND_CLEARED = "Refund for %s cleared";
    public static final String REFUND_DECLINED = "Refund for %s is declined (account or credit card closed)";
    public static final String REFUND_STOP_REQUESTED = "Refund for %s: stop check requested";
    public static final String REFUND_STOP_CHECK_CONFIRMED = "Refund for %s: stop check confirmed";
    public static final String REFUND_TASK_CREATED = "Task Created Clear Refund, Decline or Stop, %s";
    public static final String REFUND_TASK_COMPLETE_ISSUE = "Complete Task Refund Issue, %s";
    public static final String REFUND_TASK_COMPLETE_APPROVAL = "Complete Task Refund Approval, %s";
    public static final String REFUND_TASK_APPROVAL = "Task Created Refund Approval, %s";

    public static final String SET_EXPIRATION_DATE = "Agency Expiration Date set to %s";
    public static final String SET_EFFECTIVE_DATE = "Agency Effective Date set to %s";
    public static final String SET_AGENCY_CODE = "Agency %s Added";
    public static final String SET_AGENCY_NAME = "Agency Name set to %s";
    public static final String SET_PHYSICAL_ADDRESS = "Physical Address set to %s, %s, %s, %s, %s, US, %s";
    public static final String SET_MAILING_ADDRESS = "Mailing Address set to %s, %s, %s, %s, %s, US, %s";
    public static final String SET_COMMISSION_GROUPS = "Commission Group selection added %s";
    public static final String SET_CHILD_AGENCY = "Child Agency %s %s added";
    public static final String SET_TAX_ID = "Tax Id set to %s";
    public static final String SET_ALT_NAME = "Agency Alternate Name set to %s";

    public static final String UPDATE_EXPIRATION_DATE = "Agency Expiration Date set to %s from %s";
    public static final String UPDATE_EFFECTIVE_DATE = "Agency Effective Date set to %s from %s";
    public static final String UPDATE_AGENCY_NAME = "Agency Name set to %s from %s";
    public static final String UPDATE_MAILING_ADDRESS = "Mailing Address set to %s, %s, %s, %s, %s, US, %s from %s, %s, %s, %s, %s, US, %s";
    public static final String UPDATE_PHYSICAL_ADDRESS = "Physical Address set to %s, %s, %s, %s, %s, US, %s from %s, %s, %s, %s, %s, US, %s";
    public static final String UPDATE_ALT_NAME = "Agency Alternate Name set to %s from %s";
    public static final String UPDATE_TAX_ID = "Tax Id set to %s from %s";
    public static final String REMOVE_COMMISSION_GROUP = "Commission Group selection removed %s";

    public final static String CREATE_USER_BAM = "User Profile name set to %s, %s, %s";
    public final static String CREATE_EFFECTIVE_BAM = "User Profile Effective Date set to %s";
    public final static String CREATE_EXPIRATION_BAM = "User Profile Expiration Date set to %s";
    public final static String CREATE_JOB_TITLE_BAM = "User Job Title set to %s";

    public final static String UPDATE_USER_BAM = "User Profile name set to %s, %s, %s from %s, %s, %s";
    public final static String UPDATE_EFFECTIVE_BAM = "User Profile Effective Date set to %s from %s";
    public final static String UPDATE_EXPIRATION_BAM = "User Profile Expiration Date set to %s from %s";
    public final static String UPDATE_JOB_TITLE_BAM = "User Job Title set to %s from %s";
    public final static String ARCHIVED_ENDORSEMENT_EFFECTIVE_FOR_POLICY = "Archived Endorsement effective %s for Policy %s effective %s";
    public final static String APPOINTMENT_LETTER_GENERATION_INITIATED = "Appointment Letter Generation Initiated for %s";


    private BamConstants() {}
}
