package com.exigen.ren.common.enums;

public class IntegrationEnum {
    public enum IntegrationSections {
        ID_CARD("//IDCARD"),
        FIRST_RUN_DATE("//IDCARD/FIRST_RUN_DATE"),
        UNDERWRITING_CARRIER("//IDCARD/UNDERWRITING_CARRIER"),
        SITUS_STATE("//IDCARD/SITUS_STATE"),
        GROUP_NAME("//IDCARD/GROUP_NAME"),
        GROUP_NUMBER("//IDCARD/GROUP_NUMBER"),
        SUBGROUP_NUMBER("//IDCARD/SUBGROUP_NUMBER"),
        PRODUCT_SELECTION_NAME("//IDCARD/PRODUCT_SELECTION_NAME"),
        EXAM_MATERIAL_COPAY("//IDCARD/VISION_COVERAGE_INFO/EXAM_MATERIAL_COPAY"),
        ALLOWANCE("//IDCARD/VISION_COVERAGE_INFO/ALLOWANCE"),
        FIRST_NAME("//IDCARD/SUBSCRIBER/FIRST_NAME"),
        LAST_NAME("//IDCARD/SUBSCRIBER/LAST_NAME"),
        LINE1("//IDCARD/SUBSCRIBER/ADDRESS/LINE1"),
        CITY("//IDCARD/SUBSCRIBER/ADDRESS/CITY"),
        STATE("//IDCARD/SUBSCRIBER/ADDRESS/STATE"),
        ZIP_CODE("//IDCARD/SUBSCRIBER/ADDRESS/ZIPCODE"),
        DEP_FIRST_NAME("//IDCARD/DEPENDENT/FIRST_NAME"),
        DEP_LAST_NAME("//IDCARD/DEPENDENT/LAST_NAME"),
        EFF_DATE("//IDCARD/EFF_DATE"),
        SUBSCRIBER_CAID("//IDCARD/SUBSCRIBER_CAID"),
        PREMIUM("//IDCARD/PREMIUM"),
        BILLING_FREQUENCY_TYPE("//IDCARD/BILLING_FREQUENCY_TYPE"),
        ID_CARD_MAIL_TO_TYPE("//IDCARD/IDCARD_MAIL_TO_TYPE"),
        GM_FIRST_NAME("//IDCARD/GROUP_MAIL/FIRST_NAME"),
        GM_LINE1("//IDCARD/GROUP_MAIL/ADDRESS/LINE1"),
        GM_CITY("//IDCARD/GROUP_MAIL/ADDRESS/CITY"),
        GM_STATE("//IDCARD/GROUP_MAIL/ADDRESS/STATE"),
        GM_ZIP_CODE("//IDCARD/GROUP_MAIL/ADDRESS/ZIPCODE"),

        CONTRACT_POLICY_TYPE("//IDCARD/CONTRACT_POLICY_TYPE"),
        RECEIVED_DATE("//IDCARD/RECEIVED_DATE");

        String xpath;

        IntegrationSections(String xpath) {
            this.xpath = xpath;
        }

        public String getXpath() {
            return xpath;
        }
    }
}
