/* Copyright © 2016 EIS Group and/or one of its affiliates. All rights reserved. Unpublished work under U.S. copyright laws.
 CONFIDENTIAL AND TRADE SECRET INFORMATION. No portion of this work may be copied, distributed, modified, or incorporated into any other media without EIS Group prior written consent.*/
package com.exigen.ren.admin.modules.security;

//TODO(ymaliarevich): should be move to another package
public enum Privilege {
    ADVANCED_SEARCH("Advanced Search"),
    ACCESS_AGENT_CARE_QUEUE("Access Agent Care Queue"),
    CONTROL_AGENT_CARE_QUEUE("Control Agent Care Queue"),
    ACCESS_SALES_SUPPORT_QUEUE("Access Sales Support Queue"),
    CONTROL_SALES_SUPPORT_QUEUE("Control Sales Support Queue"),
    ACCESS_CASE_INSTALLATION_QUEUE("Access Case Installation Queue"),
    CONTROL_CASE_INSTALLATION_QUEUE("Control Case Installation Queue"),
    ACCESS_UW_QUEUE("Access UW Queue"),
    CONTROL_UW_QUEUE("Control UW Queue"),
    ACCESS_REN_ADMIN_QUEUE("Access Ren Admin Queue"),
    CONTROL_REN_ADMIN_QUEUE("Control Ren Admin Queue"),
    ACCESS_SERVICE_REP_QUEUE("Access Service Rep Queue"),
    CONTROL_SERVICE_REP_QUEUE("Control Service Rep Queue"),
    ACCESS_UW_APPROVALS_QUEUE("Access UW Approvals Queue"),
    CONTROL_UW_APPROVALS_QUEUE("Control UW Approvals Queue"),
    ACCESS_POLICY_SALES_SERVICE_QUEUE("Access Policy Sales & Service Queue"),
    CONTROL_POLICY_SALES_SERVICE_QUEUE("Control Policy Sales & Service Queue"),
    ACCESS_SOLD_CASE_UW_REVIEW_QUEUE("Access Sold Case UW Review Queue"),
    CONTROL_SOLD_CASE_UW_REVIEW_QUEUE("Control Sold Case UW Review Queue"),
    ALL("All"),
    BILLING_ACCOUNT_GENERATE_DRAFT_BILL("Billing Account Generate Draft Bill"),
    CLAIM_CREATE("Claim Create"),
    CLAIM_INQUIRY_CLAIM_POLICY("Claim Inquiry Claim Policy"),
    CLAIM_SECURE_CLAIM("Claim Secure Claim"),
    CLAIM_BALANCE("Claim Balance"),
    CLAIM_SUSPEND_AUTO_REDUCTION("Claim Suspend auto-reduction"),
    CLAIM_UNSUSPEND_AUTO_REDUCTION("Claim Unsuspend auto-reduction"),
    CUSTOMER_E_SIGNED_DOCS_EDIT("Customer:eSignedDocs:Edit"),
    CUSTOMER_E_SIGNED_DOCS_VIEW("Customer:eSignedDocs:View"),
    EXPERIENCE_BASED_RATING("Experience Based Rating"),
    LINK_TASKS("Link Tasks"),
    MY_WORK_TASK_INQUIRY("MyWork Task Inquiry"),
    PLATFORM_ADMIN_PROFILE_DISABLE_USER("SecurityAdmin Profile Disable User"),
    PLATFORM_ADMIN_BRANDS_TAB_ACCESS("SecurityAdmin Brands Tab Access"),
    PAYMENT_TRANSFER("Payment Transfer"),
    UNLINK_TASKS("Unlink Tasks"),
    SPECIAL_CLAIM_REVIEW_EDIT("Customer:Special Claim Review:Edit"),
    SPECIAL_CLAIM_REVIEW_VIEW("Customer:Special Claim Review:View"),
    CONFIDENTIAL_ACCOUNT_MANAGEMENT("Confidential Account Management"),
    CUSTOMER_MAIL_CARDS_TO_EDIT("Customer:mailCardsTo:Edit"),
    CUSTOMER_REORDER_CARDS_TO_EDIT("Customer:reorderCards:Edit"),
    CUSTOMER_MAIL_CARDS_TO_VIEW("Customer:mailCardsTo:View"),
    CUSTOMER_REORDER_CARDS_TO_VIEW("Customer:reorderCards:View"),
    BUNDLE_CREATE("Bundle Create"),
    CLAIM_OVERRIDE_VALUES("Claim Override Values"),
    CLAIM_SUSPEND("Claim Suspend"),
    CLAIM_CONTINUE("Claim Continue"),
    POLICY_ARCHIVE_TRANSACTION("Policy Archive Transaction"),
    OVERRIDE_RATE_REQUEST_DATE("Override Rate Request Date"),
    CLAIM_REISSUE_PAYMENT("Claim Reissue Payment"),
    GENERATE_CONSOLIDATED_STATEMENT("Generate Consolidated Statement"),
    CONSOLIDATED_STATEMENT("Set Up/Update/Remove Consolidated Statement"),
    CLAIM_ADD_OTHER_DENTAL_PAYEE("Claim Add Other Dental Payee"),
    UPDATE_PROCEDURE_CODE("Update Procedure Code"),
    CLAIM_INQUIRY_CLAIM_HISTORY("Claim Inquiry Claim History"),
    CLAIM_INFORMATION_REQUESTS("Claim Information Requests"),
    CONTROL_REVIEW_DENTAL_DOCUMENT_QUEUE("Control Review Dental Document Queue"),
    ACCESS_REVIEW_DENTAL_DOCUMENT_QUEUE("Access Review Dental Document Queue"),
    CLAIM_OVERRIDE_RULES_LEVEL_1("Claim Override Rules Level 1"),
    CLAIM_OVERRIDE_RULES_LEVEL_2("Claim Override Rules Level 2"),
    CLAIM_OVERRIDE_RULES("Claim Override Rules"),
    CLAIM_ADD_OTHER_PATIENT("Claim Add Other Patient"),
    CLAIM_INTERNATIONAL_PROVIDER("Claim International Provider"),
    ENROLLMENT_PROCESSING("EnrollmentProcessing"),
    ACCESS_PROVIDER_SERVICES_INQUIRY_QUEUE("Access Provider Services Inquiry Queue"),
    CONTROL_PROVIDER_SERVICES_INQUIRY_QUEUE("Control Provider Services Inquiry Queue"),
    ACCESS_DENTAL_CLAIM_INQUIRY_QUEUE("Access Dental Claim Inquiry Queue"),
    CONTROL_DENTAL_CLAIM_INQUIRY_QUEUE("Control Dental Claim Inquiry Queue"),
    ACCESS_LIFE_AND_DI_CLAIM_MANAGEMENT_QUEUE("Access Life & DI Claim Management Queue"),
    CONTROL_LIFE_AND_DI_CLAIM_MANAGEMENT_QUEUE("Control Life & DI Claim Management Queue"),
    ACCESS_LIFE_AND_DI_CLAIM_APPROVER_QUEUE("Access Life & DI Claim Approver Queue"),
    CONTROL_LIFE_AND_DI_CLAIM_APPROVER_QUEUE("Control Life & DI Claim Approver Queue"),
    ACCESS_DENTAL_CLAIMS_QUEUE("Access Dental Claims Queue"),
    CONTROL_DENTAL_CLAIMS_QUEUE("Control Dental Claims Queue"),
    ACCESS_ACCOUNTING_QUEUE("Access Accounting Queue"),
    CONTROL_ACCOUNTING_QUEUE("Control Accounting Queue"),
    CONTROL_CLAIM_UTILIZATION_REVIEW_QUEUE("Control Claim Utilization Review Queue"),
    CONTROL_CLAIM_UTILIZATION_REVIEW_PENDING_QUEUE("Control Claim Utilization Review Pending Queue"),
    ACCESS_CLAIM_UTILIZATION_REVIEW_QUEUE("Access Claim Utilization Review Queue"),
    ACCESS_CLAIM_UTILIZATION_REVIEW_PENDING_QUEUE("Access Claim Utilization Review Pending Queue"),
    POLICY_INQUIRY("Policy Inquiry"),
    BENEFITS_COMMISSION_CORRECTION_VIEW("BenefitsCommissionCorrectionView");

    private String id;

    Privilege(String id) {
        this.id = id;
    }

    public String get() {
        return id;
    }
}
